updated

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,7 +26,7 @@ inputs:
     description: "Do not return an error code if there are failed checks"
     required: false
   framework:
-    description: "Run only on a specific infrastructure. Supported: Kubernetes & Terraform"
+    description: "Run only on a specific infrastructure, Supported: Kubernetes & Terraform"
     required: false
   skip_framework:
     description: "Skip a specific infrastructure"
@@ -41,9 +41,6 @@ inputs:
     description: "The URL of the CSPM panel to push the scan results to."
     required: true
     default: "cspm.demo.accuknox.com"
-  label:
-    description: "The label needed to push the findings to a particular label created in AccuKnox SaaS"
-    required: true
 
 branding:
   icon: "shield"
@@ -54,37 +51,39 @@ runs:
   steps:
     - name: Run Checkov IaC Scan
       id: checkov-scan
-      run: |
-        # Build the command dynamically based on inputs
-        CMD="docker run --rm ghcr.io/bridgecrewio/checkov:3.2.21"
-        if [ -n "${{ inputs.file }}" ]; then CMD+=" -f ${{ inputs.file }}"; fi
-        if [ -n "${{ inputs.directory }}" ]; then CMD+=" -d ${{ inputs.directory }}"; fi
-        if [ -n "${{ inputs.compact }}" ]; then CMD+=" --compact=${{ inputs.compact }}"; fi
-        if [ -n "${{ inputs.quiet }}" ]; then CMD+=" --quiet"; fi
-        if [ -n "${{ inputs.output_format }}" ]; then CMD+=" --output=${{ inputs.output_format }}"; fi
-        if [ -n "${{ inputs.output_file_path }}" ]; then CMD+=" --output-file-path=${{ inputs.output_file_path }}"; fi
-        if [ -n "${{ inputs.framework }}" ]; then CMD+=" --framework=${{ inputs.framework }}"; fi
+      uses: docker://ghcr.io/bridgecrewio/checkov:3.2.21
+      with:
+        args: |
+          ${INPUT_FILE}
+          ${INPUT_DIRECTORY}
+          ${INPUT_COMPACT}
+          ${INPUT_QUIET}
+          --output ${INPUT_OUTPUT_FORMAT}
+          --output-file ${INPUT_OUTPUT_FILE_PATH}
+          ${INPUT_SOFT_FAIL}
+          ${INPUT_FRAMEWORK}
+      env:
+        INPUT_FILE: ${{ inputs.file }}
+        INPUT_DIRECTORY: ${{ inputs.directory }}
+        INPUT_COMPACT: ${{ inputs.compact }}
+        INPUT_QUIET: ${{ inputs.quiet }}
+        INPUT_OUTPUT_FORMAT: ${{ inputs.output_format }}
+        INPUT_OUTPUT_FILE_PATH: ${{ inputs.output_file_path }}
+        INPUT_SOFT_FAIL: ${{ inputs.soft_fail }}
+        INPUT_FRAMEWORK: ${{ inputs.framework }}
 
-        # Execute the constructed command
-        echo "Running command: $CMD"
-        eval $CMD
-
-        # Capture the exit code immediately
-        echo "CHECKOV_EXIT_CODE=$?" >> $GITHUB_ENV
-      continue-on-error: true # Allows the pipeline to continue even if there are Checkov errors
-      shell: bash
-
-    - name: Format the results
+    - name: Formatting the results
       run: |
         jq --arg repoLink "${{ github.server_url }}/${{ github.repository }}" --arg branch "${{ github.ref == 'refs/heads/main' && 'main' || github.head_ref }}" '. += [{"details": {"repo": $repoLink, "branch": $branch}}]' results/results_json.json > temp.json && mv temp.json results.json
       shell: bash
 
     - name: Push report to CSPM panel
       run: |
-        curl --location --request POST 'https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=IAC&label=${{ inputs.label }}&save_to_s3=false' --header 'Tenant-Id: ${{ inputs.tenant_id  }}' --header 'Authorization: Bearer ${{ inputs.token }}' --form 'file=@"results.json"'
+        curl --location --request POST 'https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=IAC&save_to_s3=false' --header 'Tenant-Id: ${{ inputs.tenant_id }}' --header 'Authorization: Bearer ${{ inputs.token }}' --form 'file=@"results.json"'
       shell: bash
 
-    - name: Fail pipeline if Checkov found issues and soft_fail is false
-      if: env.CHECKOV_EXIT_CODE != '0' && inputs.soft_fail == 'false'
-      run: exit 1 # Fail the pipeline if soft_fail is false
-      shell: bash
+    - name: Fail pipeline if Checkov scan fails
+      if: ${{ steps.checkov-scan.outcome == 'failure' }}
+      run: |
+        echo "Checkov scan failed. Breaking the pipeline."
+        exit 1
